// Generated by CoffeeScript 1.10.0
(function() {
  var BaseModel, Commits, util,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseModel = require('../BaseModel');

  util = require('util');

  Commits = (function(superClass) {
    extend(Commits, superClass);

    function Commits() {
      this.show = bind(this.show, this);
      return Commits.__super__.constructor.apply(this, arguments);
    }


    /*
    
     method            : get
     summary         : show
     description    : commit 列表
     header         : userAgent,accept
     path            : user,project,commit
     query            : diff,w
     body            : currentApp,ref
     */

    Commits.prototype.show = function(user, project, commit, params, fn) {
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("Commits::show()");
      return this.get("user/" + user + "/project/" + project + "/git/commit/" + commit, params, function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };

    return Commits;

  })(BaseModel);

  module.exports = function(client) {
    return new Commits(client);
  };

}).call(this);
