// Generated by CoffeeScript 1.10.0
(function() {
  var BaseModel, Historys, util,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseModel = require('../BaseModel');

  util = require('util');

  Historys = (function(superClass) {
    extend(Historys, superClass);

    function Historys() {
      this.get = bind(this.get, this);
      return Historys.__super__.constructor.apply(this, arguments);
    }


    /*
    
     method            : get
     summary         : get
     description    : 获取代码的历史
     header         : userAgent,accept
     path            : user,project,commits
     query            : page,pageSize
     body            : currentApp,ref,path
     */

    Historys.prototype.get = function(user, project, commits, params, fn) {
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("Historys::get()");
      return this.get("user/" + user + "/project/" + project + "/git/commits/" + commits, params, function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };

    return Historys;

  })(BaseModel);

  module.exports = function(client) {
    return new Historys(client);
  };

}).call(this);
