// Generated by CoffeeScript 1.10.0
(function() {
  var BaseModel, MergeRequests, util,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseModel = require('../BaseModel');

  util = require('util');

  MergeRequests = (function(superClass) {
    extend(MergeRequests, superClass);

    function MergeRequests() {
      this.list = bind(this.list, this);
      this.refuse = bind(this.refuse, this);
      this.merge = bind(this.merge, this);
      this.cancel = bind(this.cancel, this);
      this.update = bind(this.update, this);
      this.get = bind(this.get, this);
      this.create = bind(this.create, this);
      return MergeRequests.__super__.constructor.apply(this, arguments);
    }


    /*
    
     method            : post
     summary         : create
     description    : 创建 MergeRequest
     path            : user,project
     query            : srcBranch,desBranch,title,content,reviewers,tasks
     */

    MergeRequests.prototype.create = function(user, project, params, fn) {
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("MergeRequests::create()");
      return this.post("/api/user/" + user + "/project/" + project + "/git/merge", params, function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };


    /*
    
     method            : get
     summary         : get
     description    : 显示某个 MergeRequest
     path            : user,project,iid
     query            : diff
     */

    MergeRequests.prototype.get = function(user, project, iid, params, fn) {
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("MergeRequests::get()");
      return this.get("/api/user/" + user + "/project/" + project + "/git/merge/" + iid, params, function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };


    /*
    
     method            : put
     summary         : update
     description    : 更新某个 MergeRequest
     path            : user,project,iid
     query            : srcBranch,desBranch,title,content,reviewers,tasks
     */

    MergeRequests.prototype.update = function(user, project, iid, params, fn) {
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("MergeRequests::update()");
      return this.put("/api/user/" + user + "/project/" + project + "/git/merge/" + iid, params, function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };


    /*
    
     method            : post
     summary         : cancel
     description    : 取消 MergeRequest
     path            : user,project,iid
     */

    MergeRequests.prototype.cancel = function(user, project, iid, fn) {
      if (fn == null) {
        fn = null;
      }
      this.debug("MergeRequests::cancel()");
      return this.post("/api/user/" + user + "/project/" + project + "/git/merge/" + iid + "/cancel", function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };


    /*
    
     method            : post
     summary         : merge
     description    : 合并某个 MergeRequest
     path            : user,project,iid
     query            : message,del_source_branch
     */

    MergeRequests.prototype.merge = function(user, project, iid, params, fn) {
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("MergeRequests::merge()");
      return this.post("/api/user/" + user + "/project/" + project + "/git/merge/" + iid + "/merge", params, function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };


    /*
    
     method            : post
     summary         : refuse
     description    : 拒绝某个 MergeRequest
     path            : user,project,iid
     */

    MergeRequests.prototype.refuse = function(user, project, iid, fn) {
      if (fn == null) {
        fn = null;
      }
      this.debug("MergeRequests::refuse()");
      return this.post("/api/user/" + user + "/project/" + project + "/git/merge/" + iid + "/refuse", function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };


    /*
    
     method            : get
     summary         : list
     description    : MergeRequest 列表
     path            : user,project,status
     query            : page,pageSize
     */

    MergeRequests.prototype.list = function(user, project, status, params, fn) {
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("MergeRequests::list()");
      return this.get("/api/user/" + user + "/project/" + project + "/git/merges/" + status, params, function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };

    return MergeRequests;

  })(BaseModel);

  module.exports = function(client) {
    return new MergeRequests(client);
  };

}).call(this);
