// Generated by CoffeeScript 1.10.0
(function() {
  var BaseModel, Pull_requests, util,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseModel = require('../BaseModel');

  util = require('util');

  Pull_requests = (function(superClass) {
    extend(Pull_requests, superClass);

    function Pull_requests() {
      this.list_3 = bind(this.list_3, this);
      this.refuse_1 = bind(this.refuse_1, this);
      this.merge_1 = bind(this.merge_1, this);
      this.showCommits = bind(this.showCommits, this);
      this.comments = bind(this.comments, this);
      this.cancel_1 = bind(this.cancel_1, this);
      this.show_3 = bind(this.show_3, this);
      this.create = bind(this.create, this);
      return Pull_requests.__super__.constructor.apply(this, arguments);
    }


    /*
    
     method		: get
     operationId	: create
     description	: 创建 PullRequest
     path			: user,project
     query		: src_branch(string),des_user_name(string),des_project_name(string),des_branch(string),diff(string)
     body			:
     */

    Pull_requests.prototype.create = function(user, project, params, fn) {
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("Pull_requests::create()");
      return this.get(util.format("user/%s/project/%s/git/pull/create", user, project), params, function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };


    /*
    
     method		: get
     operationId	: show_3
     description	: 获取某个 PullRequest
     path			: user,project,iid
     query		: diff(string)
     body			:
     */

    Pull_requests.prototype.show_3 = function(user, project, iid, params, fn) {
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("Pull_requests::show_3()");
      return this.get(util.format("user/%s/project/%s/git/pull/%s", user, project, iid), params, function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };


    /*
    
     method		: post
     operationId	: cancel_1
     description	: 取消 PullRequest
     path			: user,project,iid
     query		: 
     body			:
     */

    Pull_requests.prototype.cancel_1 = function(user, project, iid, params, fn) {
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("Pull_requests::cancel_1()");
      return this.post(util.format("user/%s/project/%s/git/pull/%s/cancel", user, project, iid), params, function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };


    /*
    
     method		: get
     operationId	: comments
     description	: PullRequest 评论列表
     path			: user,project,iid
     query		: 
     body			:
     */

    Pull_requests.prototype.comments = function(user, project, iid, params, fn) {
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("Pull_requests::comments()");
      return this.get(util.format("user/%s/project/%s/git/pull/%s/comments", user, project, iid), params, function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };


    /*
    
     method		: get
     operationId	: showCommits
     description	: 获取某个 PullRequest 的评论
     path			: user,project,iid
     query		: 
     body			:
     */

    Pull_requests.prototype.showCommits = function(user, project, iid, params, fn) {
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("Pull_requests::showCommits()");
      return this.get(util.format("user/%s/project/%s/git/pull/%s/commits", user, project, iid), params, function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };


    /*
    
     method		: post
     operationId	: merge_1
     description	: 合并 PullRequest
     path			: user,project,iid
     query		: message(string)
     body			:
     */

    Pull_requests.prototype.merge_1 = function(user, project, iid, params, fn) {
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("Pull_requests::merge_1()");
      return this.post(util.format("user/%s/project/%s/git/pull/%s/merge", user, project, iid), params, function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };


    /*
    
     method		: post
     operationId	: refuse_1
     description	: 拒绝 PullRequest
     path			: user,project,iid
     query		: 
     body			:
     */

    Pull_requests.prototype.refuse_1 = function(user, project, iid, params, fn) {
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("Pull_requests::refuse_1()");
      return this.post(util.format("user/%s/project/%s/git/pull/%s/refuse", user, project, iid), params, function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };


    /*
    
     method		: get
     operationId	: list_3
     description	: PullRequest 列表
     path			: user,project,status
     query		: page(integer),pageSize(integer)
     body			:
     */

    Pull_requests.prototype.list_3 = function(user, project, status, params, fn) {
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("Pull_requests::list_3()");
      return this.get(util.format("user/%s/project/%s/git/pulls/%s", user, project, status), params, function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };

    return Pull_requests;

  })(BaseModel);

  module.exports = function(client) {
    return new Pull_requests(client);
  };

}).call(this);
