// Generated by CoffeeScript 1.10.0
(function() {
  var BaseModel, RepoFiles, util,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseModel = require('../BaseModel');

  util = require('util');

  RepoFiles = (function(superClass) {
    extend(RepoFiles, superClass);

    function RepoFiles() {
      this.create = bind(this.create, this);
      this.update = bind(this.update, this);
      this.del = bind(this.del, this);
      return RepoFiles.__super__.constructor.apply(this, arguments);
    }


    /*
    
     method            : get
     summary         : del
     description    : 删除文件
     path            : user,project,file
     body            : ref,path
     */

    RepoFiles.prototype.del = function(user, project, file, params, fn) {
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("RepoFiles::del()");
      return this.get("user/" + user + "/project/" + project + "/git/delete/" + file, params, function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };


    /*
    
     method            : get
     summary         : update
     description    : 更新文件
     path            : user,project,file
     body            : ref,path
     */

    RepoFiles.prototype.update = function(user, project, file, params, fn) {
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("RepoFiles::update()");
      return this.get("user/" + user + "/project/" + project + "/git/edit/" + file, params, function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };


    /*
    
     method            : get
     summary         : create
     description    : 新建文件
     path            : user,project,file
     body            : ref,path
     */

    RepoFiles.prototype.create = function(user, project, file, params, fn) {
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("RepoFiles::create()");
      return this.get("user/" + user + "/project/" + project + "/git/new/" + file, params, function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };

    return RepoFiles;

  })(BaseModel);

  module.exports = function(client) {
    return new RepoFiles(client);
  };

}).call(this);
