// Generated by CoffeeScript 1.10.0
(function() {
  var BaseModel, Trees, util,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseModel = require('../BaseModel');

  util = require('util');

  Trees = (function(superClass) {
    extend(Trees, superClass);

    function Trees() {
      return Trees.__super__.constructor.apply(this, arguments);
    }

    return Trees;

  })(BaseModel);

  ({

    /*
    
     method			: get
     summary 		: webhook
     description	: 目录
     header 		: userAgent,accept
     path			: user,project,tree
     body			: currentApp,ref,path
     */
    webhook: (function(_this) {
      return function(user, project, tree, params, fn) {
        if (params == null) {
          params = {};
        }
        if (fn == null) {
          fn = null;
        }
        _this.debug("Trees::webhook()");
        return _this.get("user/" + user + "/project/" + project + "/git/tree/" + tree, params, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this)
  });

  module.exports = function(client) {
    return new Trees(client);
  };

}).call(this);
