// Generated by CoffeeScript 1.10.0
(function() {
  var BaseModel, Users, util,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseModel = require('../BaseModel');

  util = require('util');

  Users = (function(superClass) {
    extend(Users, superClass);

    function Users() {
      return Users.__super__.constructor.apply(this, arguments);
    }

    return Users;

  })(BaseModel);

  ({

    /*
    
     method			: post
     summary 		: activate
     description	: 账户激活
     query			: email,key,password,confirm_password
     body			: sid
     */
    activate: (function(_this) {
      return function(params, fn) {
        if (params == null) {
          params = {};
        }
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::activate()");
        return _this.post("account/activate", params, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: post
     summary 		: generateActivatePhoneCode
     description	: 获取激活账号的手机验证码
     query			: phone
     */
    generateActivatePhoneCode: (function(_this) {
      return function(params, fn) {
        if (params == null) {
          params = {};
        }
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::generateActivatePhoneCode()");
        return _this.post("account/activate/generate_phone_code", params, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: post
     summary 		: activatePhone
     description	: 激活用手机注册的用户
     query			: phone,code,user,email,password
     body			: sid
     */
    activatePhone: (function(_this) {
      return function(params, fn) {
        if (params == null) {
          params = {};
        }
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::activatePhone()");
        return _this.post("account/activate/phone", params, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: get
     summary 		: avatar
     description	: 获取头像
     */
    avatar: (function(_this) {
      return function(fn) {
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::avatar()");
        return _this.get("account/avatar", function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: post
     summary 		: avatar
     description	: 上传设置头像
     body			: sid
     */
    avatar: (function(_this) {
      return function(params, fn) {
        if (params == null) {
          params = {};
        }
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::avatar()");
        return _this.post("account/avatar", params, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: get
     summary 		: captcha
     description	: 检查是否需要验证码
     path			: action
     body			: realRemoteAddress
     */
    captcha: (function(_this) {
      return function(action, params, fn) {
        if (params == null) {
          params = {};
        }
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::captcha()");
        return _this.get("account/captcha/" + action, params, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: get
     summary 		: changeNoticeSetting
     description	: 修改通知设置
     query			: settingType,settingContent
     */
    changeNoticeSetting: (function(_this) {
      return function(params, fn) {
        if (params == null) {
          params = {};
        }
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::changeNoticeSetting()");
        return _this.get("account/change_notice_setting", params, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: get
     summary 		: checkEmail
     description	: 检查email是否没有被注册过
     query			: key
     */
    checkEmail: (function(_this) {
      return function(params, fn) {
        if (params == null) {
          params = {};
        }
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::checkEmail()");
        return _this.get("account/check", params, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: get
     summary 		: checkPhone
     description	: 检查手机是否没有被注册过
     query			: phone
     */
    checkPhone: (function(_this) {
      return function(params, fn) {
        if (params == null) {
          params = {};
        }
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::checkPhone()");
        return _this.get("account/check/phone", params, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: post
     summary 		: checkTwoFactorAuthCode
     description	: 登录时的两步验证
     query			: code
     body			: sid
     */
    checkTwoFactorAuthCode: (function(_this) {
      return function(params, fn) {
        if (params == null) {
          params = {};
        }
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::checkTwoFactorAuthCode()");
        return _this.post("account/check_two_factor_auth_code", params, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: get
     summary 		: currentUser
     description	: 获取当前登录用户信息
     */
    currentUser: (function(_this) {
      return function(fn) {
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::currentUser()");
        return _this.get("account/current_user", function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: get
     summary 		: email
     description	: 获取当前用户的email
     */
    email: (function(_this) {
      return function(fn) {
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::email()");
        return _this.get("account/email", function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: get
     summary 		: changeNoticeSetting
     description	: 获取通知设置
     */
    changeNoticeSetting: (function(_this) {
      return function(fn) {
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::changeNoticeSetting()");
        return _this.get("account/get_notice_settings", function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: get
     summary 		: gravatar
     description	: 获取Gravatar头像
     */
    gravatar: (function(_this) {
      return function(fn) {
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::gravatar()");
        return _this.get("account/gravatar", function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: get
     summary 		: getUserByGlobalKey
     description	: 通过个性后缀获取用户信息
     path			: user
     */
    getUserByGlobalKey: (function(_this) {
      return function(user, fn) {
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::getUserByGlobalKey()");
        return _this.get("account/key/" + user, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: post
     summary 		: login
     description	: 登录
     query			: email,password,j_captcha,remember_me
     body			: sid,realRemoteAddress
     */
    login: (function(_this) {
      return function(params, fn) {
        if (params == null) {
          params = {};
        }
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::login()");
        return _this.post("account/login", params, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: post
     summary 		: generateLoginPhoneCode
     description	: 获取登录的手机验证码
     query			: phone
     */
    generateLoginPhoneCode: (function(_this) {
      return function(params, fn) {
        if (params == null) {
          params = {};
        }
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::generateLoginPhoneCode()");
        return _this.post("account/login/generate_phone_code", params, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: post
     summary 		: loginByPhone
     description	: 使用绑定过的手机号码登录
     query			: phone,code,j_captcha,remember_me
     body			: realRemoteAddress
     */
    loginByPhone: (function(_this) {
      return function(params, fn) {
        if (params == null) {
          params = {};
        }
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::loginByPhone()");
        return _this.post("account/login/phone", params, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: post
     summary 		: logout
     description	: 注销登录
     body			: sid
     */
    logout: (function(_this) {
      return function(params, fn) {
        if (params == null) {
          params = {};
        }
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::logout()");
        return _this.post("account/logout", params, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: get
     summary 		: getUserByName
     description	: 通过昵称获取用户信息
     path			: name
     */
    getUserByName: (function(_this) {
      return function(name, fn) {
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::getUserByName()");
        return _this.get("account/name/" + name, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: post
     summary 		: register
     description	: 注册
     query			: email,user,j_captcha
     body			: realRemoteAddress
     */
    register: (function(_this) {
      return function(params, fn) {
        if (params == null) {
          params = {};
        }
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::register()");
        return _this.post("account/register", params, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: post
     summary 		: generateRegisterPhoneCode
     description	: 获取注册的手机验证码
     query			: phone
     */
    generateRegisterPhoneCode: (function(_this) {
      return function(params, fn) {
        if (params == null) {
          params = {};
        }
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::generateRegisterPhoneCode()");
        return _this.post("account/register/generate_phone_code", params, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: post
     summary 		: phoneRegister
     description	: 使用手机注册
     query			: phone,code
     body			: realRemoteAddress
     */
    phoneRegister: (function(_this) {
      return function(params, fn) {
        if (params == null) {
          params = {};
        }
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::phoneRegister()");
        return _this.post("account/register/phone", params, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: post
     summary 		: avatar
     description	: 更新用户信息
     query			: tags,name,sex,phone,birthday,location,company,slogan,introduction,job,code
     body			: sid
     */
    avatar: (function(_this) {
      return function(params, fn) {
        if (params == null) {
          params = {};
        }
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::avatar()");
        return _this.post("account/update_info", params, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: post
     summary 		: updatePwd
     description	: 修改用户密码
     query			: current_password,password,confirm_password
     body			: sid
     */
    updatePwd: (function(_this) {
      return function(params, fn) {
        if (params == null) {
          params = {};
        }
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::updatePwd()");
        return _this.post("account/update_pwd", params, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: post
     summary 		: avatar
     description	: 更新头像
     query			: avatar
     body			: sid
     */
    avatar: (function(_this) {
      return function(params, fn) {
        if (params == null) {
          params = {};
        }
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::avatar()");
        return _this.post("account/updateavatar", params, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: post
     summary 		: follow
     description	: 关注用户
     query			: users
     */
    follow: (function(_this) {
      return function(params, fn) {
        if (params == null) {
          params = {};
        }
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::follow()");
        return _this.post("social/follow", params, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: get
     summary 		: follower
     description	: 关注我的用户
     query			: page,pageSize
     */
    follower: (function(_this) {
      return function(params, fn) {
        if (params == null) {
          params = {};
        }
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::follower()");
        return _this.get("social/followers", params, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: get
     summary 		: follower
     description	: 获取关注默认的用户
     path			: user
     query			: page,pageSize
     */
    follower: (function(_this) {
      return function(user, params, fn) {
        if (params == null) {
          params = {};
        }
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::follower()");
        return _this.get("social/followers/" + user, params, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: get
     summary 		: friends
     description	: 我关注的用户列表
     query			: page,pageSize
     */
    friends: (function(_this) {
      return function(params, fn) {
        if (params == null) {
          params = {};
        }
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::friends()");
        return _this.get("social/friends", params, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: get
     summary 		: friends
     description	: 指定用户的关注列表
     path			: user
     query			: page,pageSize
     */
    friends: (function(_this) {
      return function(user, params, fn) {
        if (params == null) {
          params = {};
        }
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::friends()");
        return _this.get("social/friends/" + user, params, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: get
     summary 		: relationship
     description	: 是否关注了该用户
     path			: user
     */
    relationship: (function(_this) {
      return function(user, fn) {
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::relationship()");
        return _this.get("social/relationship/" + user, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: get
     summary 		: changeNoticeSetting
     description	: 获取我关注和关注我的用户列表
     */
    changeNoticeSetting: (function(_this) {
      return function(fn) {
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::changeNoticeSetting()");
        return _this.get("social/relationships", function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: get
     summary 		: changeNoticeSetting
     description	: 获取我关注和关注我的用户列表包含成员列表
     query			: project_id
     */
    changeNoticeSetting: (function(_this) {
      return function(params, fn) {
        if (params == null) {
          params = {};
        }
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::changeNoticeSetting()");
        return _this.get("social/relationships/all", params, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: get
     summary 		: search
     description	: 搜索用户
     query			: key,page,pageSize
     */
    search: (function(_this) {
      return function(params, fn) {
        if (params == null) {
          params = {};
        }
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::search()");
        return _this.get("social/search", params, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: post
     summary 		: unfollow
     description	: 取消关注
     query			: users
     */
    unfollow: (function(_this) {
      return function(params, fn) {
        if (params == null) {
          params = {};
        }
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::unfollow()");
        return _this.post("social/unfollow", params, function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this),

    /*
    
     method			: get
     summary 		: unreadCount
     description	: 未读消息通知
     */
    unreadCount: (function(_this) {
      return function(fn) {
        if (fn == null) {
          fn = null;
        }
        _this.debug("Users::unreadCount()");
        return _this.get("social/unread_count", function(data) {
          if (fn) {
            return fn(data);
          }
        });
      };
    })(this)
  });

  module.exports = function(client) {
    return new Users(client);
  };

}).call(this);
