#!/usr/bin/env node

var program = require('commander');
var config = require('./config.js');

var Controllers = require('./controllers');

program
  .version('0.1.0')
  .description('A simple command-line tool for coding.net by nodejs');

program
  .command('login')
  .option("-t, --tmp", "Don`t save user data.")
  .action(function(options){
    if (!options.tmp_mode) {
      options.tmp = false;
    };
    Controllers.User.login(options.tmp);
  });

program
  .command('logout')
  .alias('clear')
  .description('Logout and clear local data.')
  .action(function(){
    console.log('Login out');
  });

program
  .command('info')
  .description('Prints out current user info')
  .action(function(){

  });

program
  .command('project')
  .description('')
  .option("-ls, --list", "")
  .option("-n, --new", "")
  .action(function(options){
  });

program
  .command('task <project name>')
  .description('')
  .option("-ls, --list", "")
  .option("-n, --new", "")
  .option("-rm, --remove", "")
  .option("-up, --updata", "")
  .action(function(project_name, options){
  });

program.parse(process.argv);