// Generated by CoffeeScript 1.10.0
(function() {
  var BaseModel, Merge_requests, util,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseModel = require('../BaseModel');

  util = require('util');

  Merge_requests = (function(superClass) {
    extend(Merge_requests, superClass);

    function Merge_requests() {
      this.list_2 = bind(this.list_2, this);
      this.refuse = bind(this.refuse, this);
      this.merge = bind(this.merge, this);
      this.cancel = bind(this.cancel, this);
      this.show_2 = bind(this.show_2, this);
      this.do_create = bind(this.do_create, this);
      return Merge_requests.__super__.constructor.apply(this, arguments);
    }


    /*
    
     method		: post
     operationId	: do_create
     description	: 创建 MergeRequest
     path			: user,project
     query		: srcBranch(string),desBranch(string),title(string),content(string),reviewers(string),tasks(string)
     body			:
     */

    Merge_requests.prototype.do_create = function(user, project, params, fn) {
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("Merge_requests::do_create()");
      return this.post(util.format("user/%s/project/%s/git/merge", user, project), params, function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };


    /*
    
     method		: get
     operationId	: show_2
     description	: 显示某个 MergeRequest
     path			: user,project,iid
     query		: diff(string)
     body			:
     */

    Merge_requests.prototype.show_2 = function(user, project, iid, params, fn) {
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("Merge_requests::show_2()");
      return this.get(util.format("user/%s/project/%s/git/merge/%s", user, project, iid), params, function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };


    /*
    
     method		: post
     operationId	: cancel
     description	: 取消 MergeRequest
     path			: user,project,iid
     query		: 
     body			:
     */

    Merge_requests.prototype.cancel = function(user, project, iid, params, fn) {
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("Merge_requests::cancel()");
      return this.post(util.format("user/%s/project/%s/git/merge/%s/cancel", user, project, iid), params, function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };


    /*
    
     method		: post
     operationId	: merge
     description	: 合并某个 MergeRequest
     path			: user,project,iid
     query		: message(string),del_source_branch(boolean)
     body			:
     */

    Merge_requests.prototype.merge = function(user, project, iid, params, fn) {
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("Merge_requests::merge()");
      return this.post(util.format("user/%s/project/%s/git/merge/%s/merge", user, project, iid), params, function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };


    /*
    
     method		: post
     operationId	: refuse
     description	: 拒绝某个 MergeRequest
     path			: user,project,iid
     query		: 
     body			:
     */

    Merge_requests.prototype.refuse = function(user, project, iid, params, fn) {
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("Merge_requests::refuse()");
      return this.post(util.format("user/%s/project/%s/git/merge/%s/refuse", user, project, iid), params, function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };


    /*
    
     method		: get
     operationId	: list_2
     description	: MergeRequest 列表
     path			: user,project,status
     query		: page(integer),pageSize(integer)
     body			:
     */

    Merge_requests.prototype.list_2 = function(user, project, status, params, fn) {
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("Merge_requests::list_2()");
      return this.get(util.format("user/%s/project/%s/git/merges/%s", user, project, status), params, function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };

    return Merge_requests;

  })(BaseModel);

  module.exports = function(client) {
    return new Merge_requests(client);
  };

}).call(this);
