
# Generated by gitai 0.1.2

BaseModel = require '../BaseModel'
util = require 'util'

class Branchs extends BaseModel


  ###

   method            : post
   summary         : default
   description    : 设置默认分支
   path            : user,project
   query            : branch_name

  ###

  default: (user,project,params = {}, fn = null) =>
    @debug "Branchs::default()"
    @post "/api/user/#{user}/project/#{project}/git/branch/default", params, (data) ->
      fn data if fn


  ###

   method            : get
   summary         : listBranches
   description    : 分页显示分支列表
   path            : user,project
   query            : page,pageSize

  ###

  listBranches: (user,project,params = {}, fn = null) =>
    @debug "Branchs::listBranches()"
    @get "/api/user/#{user}/project/#{project}/git/branches", params, (data) ->
      fn data if fn


  ###

   method            : post
   summary         : create
   description    : 新建分支
   path            : user,project
   query            : branch_name,start_point

  ###

  create: (user,project,params = {}, fn = null) =>
    @debug "Branchs::create()"
    @post "/api/user/#{user}/project/#{project}/git/branches/create", params, (data) ->
      fn data if fn


  ###

   method            : post
   summary         : del
   description    : 删除分支
   path            : user,project
   query            : branch_name

  ###

  del: (user,project,params = {}, fn = null) =>
    @debug "Branchs::del()"
    @post "/api/user/#{user}/project/#{project}/git/branches/delete", params, (data) ->
      fn data if fn


  ###

   method            : post
   summary         : addMember
   description    : 添加保护分支成员
   path            : user,project
   query            : branch_name,target_global_key

  ###

  addMember: (user,project,params = {}, fn = null) =>
    @debug "Branchs::addMember()"
    @post "/api/user/#{user}/project/#{project}/git/branches/protected_branch/add_member", params, (data) ->
      fn data if fn


  ###

   method            : post
   summary         : protectedBranch
   description    : 取消保护分支
   path            : user,project
   query            : branch_name

  ###

  protectedBranch: (user,project,params = {}, fn = null) =>
    @debug "Branchs::protectedBranch()"
    @post "/api/user/#{user}/project/#{project}/git/branches/protected_branch/disable", params, (data) ->
      fn data if fn


  ###

   method            : post
   summary         : protectedBranch
   description    : 设置保护分支
   path            : user,project
   query            : branch_name

  ###

  protectedBranch: (user,project,params = {}, fn = null) =>
    @debug "Branchs::protectedBranch()"
    @post "/api/user/#{user}/project/#{project}/git/branches/protected_branch/enable", params, (data) ->
      fn data if fn


  ###

   method            : get
   summary         : members
   description    : 列出保护分支中的成员
   path            : user,project
   query            : branch_name

  ###

  members: (user,project,params = {}, fn = null) =>
    @debug "Branchs::members()"
    @get "/api/user/#{user}/project/#{project}/git/branches/protected_branch/members", params, (data) ->
      fn data if fn


  ###

   method            : post
   summary         : deleteMember
   description    : 删除保护分支成员
   path            : user,project
   query            : branch_name,target_global_key

  ###

  deleteMember: (user,project,params = {}, fn = null) =>
    @debug "Branchs::deleteMember()"
    @post "/api/user/#{user}/project/#{project}/git/branches/protected_branch/remove_member", params, (data) ->
      fn data if fn



module.exports = (client) -> new Branchs client