
# Generated by gitai 0.1.2

BaseModel = require '../BaseModel'
util = require 'util'

class Files extends BaseModel


  ###

   method            : get
   summary         : checkExisted
   description    : 检查目录下是否有同名的文件
   path            : user,project,dir
   body            : names

  ###

  checkExisted: (user,project,dir,params = {}, fn = null) =>
    @debug "Files::checkExisted()"
    @get "user/#{user}/project/#{project}/dir/#{dir}/files/existed", params, (data) ->
      fn data if fn


  ###

   method            : post
   summary         : uploadNewVersion
   description    : 上传文件新版本
   path            : user,project

  ###

  uploadNewVersion: (user,project,fn = null) =>
    @debug "Files::uploadNewVersion()"
    @post "user/#{user}/project/#{project}/file/history/upload", (data) ->
      fn data if fn


  ###

   method            : delete
   summary         : view
   description    : 删除文件
   path            : user,project
   body            : fileIds

  ###

  view: (user,project,params = {}, fn = null) =>
    @debug "Files::view()"
    @delete "user/#{user}/project/#{project}/files", params, (data) ->
      fn data if fn


  ###

   method            : delete
   summary         : history
   description    : 删除文件历史
   path            : user,project,id

  ###

  history: (user,project,id,fn = null) =>
    @debug "Files::history()"
    @delete "user/#{user}/project/#{project}/files/histories/#{id}", (data) ->
      fn data if fn


  ###

   method            : get
   summary         : download
   description    : 下载历史文件版本
   path            : user,project,id

  ###

  download: (user,project,id,fn = null) =>
    @debug "Files::download()"
    @get "user/#{user}/project/#{project}/files/histories/#{id}/download", (data) ->
      fn data if fn


  ###

   method            : post
   summary         : upload
   description    : 上传私有项目的图片
   path            : user,project

  ###

  upload: (user,project,fn = null) =>
    @debug "Files::upload()"
    @post "user/#{user}/project/#{project}/files/upload", (data) ->
      fn data if fn


  ###

   method            : get
   summary         : download
   description    : 文件下载
   path            : user,project,fileId

  ###

  download: (user,project,fileId,fn = null) =>
    @debug "Files::download()"
    @get "user/#{user}/project/#{project}/files/#{fileId}/download", (data) ->
      fn data if fn


  ###

   method            : get
   summary         : download
   description    : 文件下载URL
   path            : user,project,fileId

  ###

  download: (user,project,fileId,fn = null) =>
    @debug "Files::download()"
    @get "user/#{user}/project/#{project}/files/#{fileId}/download/url", (data) ->
      fn data if fn


  ###

   method            : post
   summary         : edit
   description    : 编辑文件
   path            : user,project,fileId
   query            : name,content,fileId

  ###

  edit: (user,project,fileId,params = {}, fn = null) =>
    @debug "Files::edit()"
    @post "user/#{user}/project/#{project}/files/#{fileId}/edit", params, (data) ->
      fn data if fn


  ###

   method            : get
   summary         : view
   description    : 查看文件
   path            : user,project,fileId
   query            : type,width,height,flag

  ###

  view: (user,project,fileId,params = {}, fn = null) =>
    @debug "Files::view()"
    @get "user/#{user}/project/#{project}/files/#{fileId}/view", params, (data) ->
      fn data if fn


  ###

   method            : get
   summary         : preview
   description    : 图片预览
   path            : user,project,fileId
   query            : type,width,height

  ###

  preview: (user,project,fileId,params = {}, fn = null) =>
    @debug "Files::preview()"
    @get "user/#{user}/project/#{project}/files/#{fileId}/view/image", params, (data) ->
      fn data if fn


  ###

   method            : post
   summary         : updateFileRemark
   description    : 修改历史版本备注
   path            : user,project,file_id,history_id
   query            : remark

  ###

  updateFileRemark: (user,project,file_id,history_id,params = {}, fn = null) =>
    @debug "Files::updateFileRemark()"
    @post "user/#{user}/project/#{project}/files/#{file_id}/histories/#{history_id}/remark", params, (data) ->
      fn data if fn


  ###

   method            : post
   summary         : create
   description    : 创建文件
   path            : user,project,folderId
   query            : projectFile.deleted_at,projectFile.projects_id,projectFile.files_id,projectFile.comments,projectFile.id,folder.owner_id,folder.parent_id,folder.created_at,folder.updated_at,folder.type,folder.size,folder.name,folder.storage_type,folder.storage_key,folder.history_id,folder.id,name,content,folderId

  ###

  create: (user,project,folderId,params = {}, fn = null) =>
    @debug "Files::create()"
    @post "user/#{user}/project/#{project}/files/#{folderId}/files", params, (data) ->
      fn data if fn


  ###

   method            : get
   summary         : history
   description    : 文件历史
   path            : user,project,id
   query            : type,width,height

  ###

  history: (user,project,id,params = {}, fn = null) =>
    @debug "Files::history()"
    @get "user/#{user}/project/#{project}/files/#{id}/histories", params, (data) ->
      fn data if fn


  ###

   method            : post
   summary         : mkdir
   description    : 创建文件夹
   path            : user,project
   query            : name,parentId

  ###

  mkdir: (user,project,params = {}, fn = null) =>
    @debug "Files::mkdir()"
    @post "user/#{user}/project/#{project}/folder", params, (data) ->
      fn data if fn


  ###

   method            : delete
   summary         : mkdir
   description    : 删除文件夹
   path            : user,project

  ###

  mkdir: (user,project,fn = null) =>
    @debug "Files::mkdir()"
    @delete "user/#{user}/project/#{project}/folder", (data) ->
      fn data if fn


  ###

   method            : put
   summary         : move
   description    : 移动文件
   path            : user,project,dirId
   query            : fileId

  ###

  move: (user,project,dirId,params = {}, fn = null) =>
    @debug "Files::move()"
    @put "user/#{user}/project/#{project}/folder/#{dirId}/move", params, (data) ->
      fn data if fn


  ###

   method            : put
   summary         : renameFolder
   description    : 重命名文件夹
   path            : user,project,dir
   query            : name

  ###

  renameFolder: (user,project,dir,params = {}, fn = null) =>
    @debug "Files::renameFolder()"
    @put "user/#{user}/project/#{project}/folder/#{dir}", params, (data) ->
      fn data if fn


  ###

   method            : get
   summary         : files
   description    : 列出某目录下的文件
   path            : user,project,dir
   query            : type,width,height,page,pageSize

  ###

  files: (user,project,dir,params = {}, fn = null) =>
    @debug "Files::files()"
    @get "user/#{user}/project/#{project}/folder/#{dir}/files", params, (data) ->
      fn data if fn


  ###

   method            : get
   summary         : folders
   description    : 列出所有一级目录
   path            : user,project
   query            : page,pageSize

  ###

  folders: (user,project,params = {}, fn = null) =>
    @debug "Files::folders()"
    @get "user/#{user}/project/#{project}/folders", params, (data) ->
      fn data if fn


  ###

   method            : get
   summary         : folders
   description    : 列出所有目录
   path            : user,project
   query            : page,pageSize

  ###

  folders: (user,project,params = {}, fn = null) =>
    @debug "Files::folders()"
    @get "user/#{user}/project/#{project}/folders/all", params, (data) ->
      fn data if fn


  ###

   method            : get
   summary         : count
   description    : 获取文件夹的文件数
   path            : user,project

  ###

  count: (user,project,fn = null) =>
    @debug "Files::count()"
    @get "user/#{user}/project/#{project}/folders/file_count/all", (data) ->
      fn data if fn



module.exports = (client) -> new Files client