
# Generated by gitai 0.1.2

BaseModel = require '../BaseModel'
util = require 'util'

class Historys extends BaseModel


  ###

   method            : get
   summary         : get
   description    : 获取代码的历史
   header         : userAgent,accept
   path            : user,project,commits
   query            : page,pageSize
   body            : currentApp,ref,path

  ###

  get: (user,project,commits,params = {}, fn = null) =>
    @debug "Historys::get()"
    @get "user/#{user}/project/#{project}/git/commits/#{commits}", params, (data) ->
      fn data if fn



module.exports = (client) -> new Historys client