
# Generated by gitai 0.1.2

BaseModel = require '../BaseModel'
util = require 'util'

class Keys extends BaseModel


  ###

   method            : get
   summary         : get
   description    : 通过KeyId获取个人公钥
   path            : user,keyId

  ###

  get: (user,keyId,fn = null) =>
    @debug "Keys::get()"
    @get "/api/user/#{user}/key/#{keyId}", (data) ->
      fn data if fn


  ###

   method            : delete
   summary         : key
   description    : 删除个人公钥
   path            : user,keyId

  ###

  key: (user,keyId,fn = null) =>
    @debug "Keys::key()"
    @delete "/api/user/#{user}/key/#{keyId}", (data) ->
      fn data if fn


  ###

   method            : get
   summary         : list
   description    : 列出个人公钥
   path            : user
   query            : withIDEKey

  ###

  list: (user,params = {}, fn = null) =>
    @debug "Keys::list()"
    @get "/api/user/#{user}/keys", params, (data) ->
      fn data if fn


  ###

   method            : post
   summary         : create
   description    : 创建个人公钥
   path            : user
   query            : title,content

  ###

  create: (user,params = {}, fn = null) =>
    @debug "Keys::create()"
    @post "/api/user/#{user}/keys", params, (data) ->
      fn data if fn


  ###

   method            : post
   summary         : webhook
   description    : 绑定部署公钥
   path            : user,project,id

  ###

  webhook: (user,project,id,fn = null) =>
    @debug "Keys::webhook()"
    @post "/api/user/#{user}/project/#{project}/git/bind_deploy_key/#{id}", (data) ->
      fn data if fn


  ###

   method            : post
   summary         : webhook
   description    : 新建部署公钥
   path            : user,project
   query            : title,content

  ###

  webhook: (user,project,params = {}, fn = null) =>
    @debug "Keys::webhook()"
    @post "/api/user/#{user}/project/#{project}/git/deploy_key", params, (data) ->
      fn data if fn


  ###

   method            : get
   summary         : list
   description    : 列出部署公钥
   path            : user,project

  ###

  list: (user,project,fn = null) =>
    @debug "Keys::list()"
    @get "/api/user/#{user}/project/#{project}/git/deploy_keys", (data) ->
      fn data if fn


  ###

   method            : post
   summary         : webhook
   description    : 解绑部署公钥
   path            : user,project,id

  ###

  webhook: (user,project,id,fn = null) =>
    @debug "Keys::webhook()"
    @post "/api/user/#{user}/project/#{project}/git/unbind_deploy_key/#{id}", (data) ->
      fn data if fn



module.exports = (client) -> new Keys client