
# Generated by gitai 0.1.2

BaseModel = require '../BaseModel'
util = require 'util'

class Projects extends BaseModel


  ###

   method            : get
   summary         : pinProject
   description    : 获取常用项目列表
   query            : page,pageSize

  ###

  pinProject: (params = {}, fn = null) =>
    @debug "Projects::pinProject()"
    @get "/api/account/projects/pin", params, (data) ->
      fn data if fn


  ###

   method            : post
   summary         : pinProject
   description    : 设置常用项目
   body            : ids

  ###

  pinProject: (params = {}, fn = null) =>
    @debug "Projects::pinProject()"
    @post "/api/account/projects/pin", params, (data) ->
      fn data if fn


  ###

   method            : delete
   summary         : pinProject
   description    : 取消常用项目
   body            : ids

  ###

  pinProject: (params = {}, fn = null) =>
    @debug "Projects::pinProject()"
    @delete "/api/account/projects/pin", params, (data) ->
      fn data if fn


  ###

   method            : put
   summary         : update
   description    : 更新项目信息
   query            : id,name,description

  ###

  update: (params = {}, fn = null) =>
    @debug "Projects::update()"
    @put "/api/project", params, (data) ->
      fn data if fn


  ###

   method            : get
   summary         : recommendedList
   description    : 推荐项目list

  ###

  recommendedList: (fn = null) =>
    @debug "Projects::recommendedList()"
    @get "/api/projects/recommended", (data) ->
      fn data if fn


  ###

   method            : get
   summary         : publicProjects
   description    : 公有项目列表
   query            : page,pageSize

  ###

  publicProjects: (params = {}, fn = null) =>
    @debug "Projects::publicProjects()"
    @get "/api/public/all", params, (data) ->
      fn data if fn


  ###

   method            : get
   summary         : queryByName
   description    : 通过名称查询
   path            : user,project

  ###

  queryByName: (user,project,fn = null) =>
    @debug "Projects::queryByName()"
    @get "/api/user/#{user}/project/#{project}", (data) ->
      fn data if fn


  ###

   method            : delete
   summary         : deleteProject
   description    : 删除项目
   path            : user,project
   query            : name

  ###

  deleteProject: (user,project,params = {}, fn = null) =>
    @debug "Projects::deleteProject()"
    @delete "/api/user/#{user}/project/#{project}", params, (data) ->
      fn data if fn


  ###

   method            : post
   summary         : setProjectIcon
   description    : 设置项目图标
   path            : user,project

  ###

  setProjectIcon: (user,project,fn = null) =>
    @debug "Projects::setProjectIcon()"
    @post "/api/user/#{user}/project/#{project}/project_icon", (data) ->
      fn data if fn


  ###

   method            : post
   summary         : star
   description    : 收藏项目
   path            : user,project

  ###

  star: (user,project,fn = null) =>
    @debug "Projects::star()"
    @post "/api/user/#{user}/project/#{project}/star", (data) ->
      fn data if fn


  ###

   method            : post
   summary         : stared
   description    : 项目是否被收藏
   path            : user,project

  ###

  stared: (user,project,fn = null) =>
    @debug "Projects::stared()"
    @post "/api/user/#{user}/project/#{project}/stared", (data) ->
      fn data if fn


  ###

   method            : post
   summary         : unstar
   description    : 项目取消收藏
   path            : user,project

  ###

  unstar: (user,project,fn = null) =>
    @debug "Projects::unstar()"
    @post "/api/user/#{user}/project/#{project}/unstar", (data) ->
      fn data if fn


  ###

   method            : post
   summary         : unwatch
   description    : 项目取消关注
   path            : user,project

  ###

  unwatch: (user,project,fn = null) =>
    @debug "Projects::unwatch()"
    @post "/api/user/#{user}/project/#{project}/unwatch", (data) ->
      fn data if fn


  ###

   method            : get
   summary         : visitProject
   description    : 更新项目阅读时间
   path            : user,project

  ###

  visitProject: (user,project,fn = null) =>
    @debug "Projects::visitProject()"
    @get "/api/user/#{user}/project/#{project}/update_visit", (data) ->
      fn data if fn


  ###

   method            : post
   summary         : watch
   description    : 关注项目
   path            : user,project

  ###

  watch: (user,project,fn = null) =>
    @debug "Projects::watch()"
    @post "/api/user/#{user}/project/#{project}/watch", (data) ->
      fn data if fn


  ###

   method            : post
   summary         : watched
   description    : 项目是否被关注
   path            : user,project

  ###

  watched: (user,project,fn = null) =>
    @debug "Projects::watched()"
    @post "/api/user/#{user}/project/#{project}/watched", (data) ->
      fn data if fn


  ###

   method            : get
   summary         : watched
   description    : 项目关注者
   path            : user,project

  ###

  watched: (user,project,fn = null) =>
    @debug "Projects::watched()"
    @get "/api/user/#{user}/project/#{project}/watchers", (data) ->
      fn data if fn


  ###

   method            : get
   summary         : projectList
   description    : 我的项目列表
   query            : type,sort,page,pageSize

  ###

  projectList: (params = {}, fn = null) =>
    @debug "Projects::projectList()"
    @get "/api/user/projects", params, (data) ->
      fn data if fn


  ###

   method            : get
   summary         : privateProjects
   description    : 私有项目列表
   query            : type,page,pageSize

  ###

  privateProjects: (params = {}, fn = null) =>
    @debug "Projects::privateProjects()"
    @get "/api/user/projects/private", params, (data) ->
      fn data if fn


  ###

   method            : post
   summary         : privateProjects
   description    : 私有项目列表
   query            : type,page,pageSize

  ###

  privateProjects: (params = {}, fn = null) =>
    @debug "Projects::privateProjects()"
    @post "/api/user/projects/private", params, (data) ->
      fn data if fn


  ###

   method            : put
   summary         : privateProjects
   description    : 私有项目列表
   query            : type,page,pageSize

  ###

  privateProjects: (params = {}, fn = null) =>
    @debug "Projects::privateProjects()"
    @put "/api/user/projects/private", params, (data) ->
      fn data if fn


  ###

   method            : delete
   summary         : privateProjects
   description    : 私有项目列表
   query            : type,page,pageSize

  ###

  privateProjects: (params = {}, fn = null) =>
    @debug "Projects::privateProjects()"
    @delete "/api/user/projects/private", params, (data) ->
      fn data if fn


  ###

   method            : options
   summary         : privateProjects
   description    : 私有项目列表
   query            : type,page,pageSize

  ###

  privateProjects: (params = {}, fn = null) =>
    @debug "Projects::privateProjects()"
    @options "/api/user/projects/private", params, (data) ->
      fn data if fn


  ###

   method            : patch
   summary         : privateProjects
   description    : 私有项目列表
   query            : type,page,pageSize

  ###

  privateProjects: (params = {}, fn = null) =>
    @debug "Projects::privateProjects()"
    @patch "/api/user/projects/private", params, (data) ->
      fn data if fn


  ###

   method            : post
   summary         : createProject
   description    : 创建项目
   path            : user
   formData        : name,description,type,gitEnabled,gitIgnore,gitReadmeEnabled,gitLicense,importFrom,vcsType,icon

  ###

  createProject: (user,params = {}, fn = null) =>
    @debug "Projects::createProject()"
    @post "/api/user/#{user}/project", params, (data) ->
      fn data if fn


  ###

   method            : get
   summary         : publicProjects
   description    : 公有项目列表
   path            : user
   query            : type,page,pageSize

  ###

  publicProjects: (user,params = {}, fn = null) =>
    @debug "Projects::publicProjects()"
    @get "/api/user/#{user}/projects/public", params, (data) ->
      fn data if fn


  ###

   method            : post
   summary         : publicProjects
   description    : 公有项目列表
   path            : user
   query            : type,page,pageSize

  ###

  publicProjects: (user,params = {}, fn = null) =>
    @debug "Projects::publicProjects()"
    @post "/api/user/#{user}/projects/public", params, (data) ->
      fn data if fn


  ###

   method            : put
   summary         : publicProjects
   description    : 公有项目列表
   path            : user
   query            : type,page,pageSize

  ###

  publicProjects: (user,params = {}, fn = null) =>
    @debug "Projects::publicProjects()"
    @put "/api/user/#{user}/projects/public", params, (data) ->
      fn data if fn


  ###

   method            : delete
   summary         : publicProjects
   description    : 公有项目列表
   path            : user
   query            : type,page,pageSize

  ###

  publicProjects: (user,params = {}, fn = null) =>
    @debug "Projects::publicProjects()"
    @delete "/api/user/#{user}/projects/public", params, (data) ->
      fn data if fn


  ###

   method            : options
   summary         : publicProjects
   description    : 公有项目列表
   path            : user
   query            : type,page,pageSize

  ###

  publicProjects: (user,params = {}, fn = null) =>
    @debug "Projects::publicProjects()"
    @options "/api/user/#{user}/projects/public", params, (data) ->
      fn data if fn


  ###

   method            : patch
   summary         : publicProjects
   description    : 公有项目列表
   path            : user
   query            : type,page,pageSize

  ###

  publicProjects: (user,params = {}, fn = null) =>
    @debug "Projects::publicProjects()"
    @patch "/api/user/#{user}/projects/public", params, (data) ->
      fn data if fn



module.exports = (client) -> new Projects client