
# Generated by gitai 0.1.2

BaseModel = require '../BaseModel'
util = require 'util'

class Trees extends BaseModel


  ###

   method            : get
   summary         : webhook
   description    : 目录
   header         : userAgent,accept
   path            : user,project,tree
   body            : currentApp,ref,path

  ###

  webhook: (user,project,tree,params = {}, fn = null) =>
    @debug "Trees::webhook()"
    @get "user/#{user}/project/#{project}/git/tree/#{tree}", params, (data) ->
      fn data if fn



module.exports = (client) -> new Trees client